// Bilingual content. Replace placeholder text with real values.
window.PORTFOLIO_CONTENT = {
  meta: {
    name:    { en: "Kun Sovathana",                        km: "គុណ សុវត្ថនា" },
    rank:    { en: "First Lieutenant",                     km: "អនុសេនីយ៍ឯក" },
    rankShort: { en: "1LT",                                km: "អន.ឯក" },
    role:    { en: "Airborne Infantry Officer",            km: "នាយទាហាន​អ៊ីនហ្វង់ទ្រី​ចូលដោយឆ័ត្រ" },
    unit:    { en: "Brigade 911 · Royal Cambodian Armed Forces", km: "កងពលលេខ ៩១១ · កងយោធពលខេមរភូមិន្ទ" },
    location:{ en: "Phnom Penh, Kingdom of Cambodia",      km: "ភ្នំពេញ ព្រះរាជាណាចក្រកម្ពុជា" },
    yos:     { en: "9 years of service",                   km: "៩ ឆ្នាំ​នៃ​ការ​បម្រើ" },
    serial:  { en: "Service № 04-227-911",                 km: "លេខ​ប្រ​ចា​ំ​ការ ០៤-២២៧-៩១១" },
    motto:   { en: "Discipline. Duty. Devotion.",          km: "វិន័យ · កាតព្វកិច្ច · សេចក្តីស្រឡាញ់ជាតិ" },
  },

  nav: [
    { id: "home",        en: "Profile",         km: "ទម្រង់" },
    { id: "timeline",    en: "Career",          km: "មុខងារ" },
    { id: "achievements",en: "Achievements",    km: "សមិទ្ធផល" },
    { id: "education",   en: "Training",        km: "វគ្គបណ្តុះបណ្តាល" },
    { id: "awards",      en: "Awards",          km: "​គ្រឿងឥស្សរិយយស" },
    { id: "skills",      en: "Skills",          km: "ជំនាញ" },
    { id: "languages",   en: "Languages",       km: "ភាសា" },
    { id: "references",  en: "References",      km: "ឯកសារយោង" },
    { id: "contact",     en: "Contact",         km: "ទំនាក់ទំនង" },
  ],

  ui: {
    langSwitch: { en: "ខ្មែរ", km: "EN" },
    pageOf:     { en: (i,n)=>`${String(i).padStart(2,"0")} / ${String(n).padStart(2,"0")}`,
                  km: (i,n)=>`${String(i).padStart(2,"0")} / ${String(n).padStart(2,"0")}` },
    sectionLabel: { en: "Dossier",  km: "ឯកសារ" },
    confidential: { en: "For internal review · Promotion board use", km: "សម្រាប់​ការ​ត្រួត​ពិនិត្យ​ផ្ទៃ​ក្នុង · គណៈ​កម្មការ​តម្លើង​ឋានន្តរ​សក្ដិ" },
    next: { en: "Next", km: "បន្ទាប់" },
    prev: { en: "Previous", km: "ត្រឡប់ក្រោយ" },
  },

  home: {
    eyebrow: { en: "Officer Portfolio · Edition I",            km: "ឯកសារ​នាយទាហាន · បោះពុម្ពលើកទី១" },
    headline:{ en: "A record of service to the Kingdom of Cambodia.",
               km: "កំណត់ត្រា​នៃ​ការ​បម្រើ​ដល់​ព្រះរាជា​ណាចក្រ​កម្ពុជា។" },
    summary: {
      en: "Airborne infantry officer with nine years of progressive command experience across reconnaissance, joint training, and humanitarian operations. Trusted with sensitive equipment portfolios exceeding US$3.2 million and the development of fifty-plus enlisted soldiers. Calm under tempo, precise on the radio, and relentless about standards.",
      km: "នាយទាហាន​អ៊ីនហ្វង់ទ្រី​ចូលដោយឆ័ត្រ ដែល​មាន​បទពិសោធន៍​ក្នុង​ការ​បញ្ជា​ការ​អស់​រយៈ​ពេល​ប្រាំបួនឆ្នាំ ខាងផ្នែក​ស៊ើបការណ៍​សម្ងាត់ ការ​បណ្តុះបណ្តាល​រួម និង​ប្រតិបត្តិការ​មនុស្សធម៌។ ត្រូវ​បាន​ផ្ដល់​ជំនឿ​ទុក​ចិត្ត​លើ​បរិក្ខារ​រសើប​លើស ៣,២ លាន​ដុល្លារ​អាមេរិក និង​ការ​អភិវឌ្ឍ​ទាហាន​ជំនួយ​ការ​ជាង​ហាសិបនាក់។ ស្ងប់ស្ងាត់​ក្នុង​ស្ថានភាព​បន្ទាន់ ច្បាស់​លាស់​លើ​វិទ្យុ និង​មិន​អនុគ្រោះ​ចំពោះ​បទដ្ឋាន។"
    },
    coreValues: [
      { label: { en: "Leadership style", km: "របៀប​ដឹក​នាំ" },
        body:  { en: "Calm, by-example. I move first under load.", km: "ស្ងប់ស្ងាត់ ដោយ​ជា​គំរូ។ ខ្ញុំ​ឆ្លើយ​តប​មុន​គេ​ក្រោម​សម្ពាធ។" } },
      { label: { en: "Specialty",       km: "ឯកទេស" },
        body:  { en: "Airborne ops · small-unit tactics · joint coordination.", km: "ប្រតិបត្តិការ​ឆ័ត្រ · យុទ្ធវិធី​ឯកតា​តូច · សម្របសម្រួល​រួម។" } },
      { label: { en: "Currently",       km: "បច្ចុប្បន្ន" },
        body:  { en: "Platoon Leader, B Co · Brigade 911.", km: "មេបញ្ជាការ​ភូមិ​ភាគ ក្រុម​ក · កងពលលេខ ៩១១។" } },
    ],
    stats: [
      { k:{en:"Soldiers led",km:"ទាហាន​ដឹក​នាំ"},               v:"57"  },
      { k:{en:"Live-fire exercises",km:"លំហាត់​បាញ់​ស្រស់"},     v:"24"  },
      { k:{en:"Joint trainings",km:"ការ​បណ្តុះបណ្តាល​រួម"},     v:"6"   },
      { k:{en:"Sensitive items",km:"បរិក្ខារ​រសើប (USD)"},      v:"$3.2M"},
    ],
  },

  timeline: [
    { year: "2024 — Present",
      title: { en: "Platoon Leader, Bravo Company",            km: "មេបញ្ជាការ​ភូមិភាគ ក្រុម​ខ" },
      unit:  { en: "Brigade 911 · Phnom Penh",                 km: "កងពលលេខ ៩១១ · ភ្នំពេញ" },
      body:  { en: "Lead a 32-soldier airborne infantry platoon. Own the training calendar, marksmanship qualifications, and equipment readiness. Selected to plan the brigade's quarterly live-jump exercise.",
               km: "ដឹក​នាំ​ភូមិភាគ​អ៊ីនហ្វង់ទ្រី​ចូល​ដោយ​ឆ័ត្រ ចំនួន ៣២​នាក់។ ទទួល​ខុស​ត្រូវ​លើ​កាលវិភាគ​បណ្តុះបណ្តាល លក្ខណៈ​សម្បត្តិ​បាញ់​ផ្ទាល់ និង​ការ​ត្រៀម​បរិក្ខារ។ ត្រូវ​បាន​ជ្រើស​រើស​ដើម្បី​រៀបចំ​លំហាត់​លោត​ឆ័ត្រ​ប្រចាំ​ត្រីមាស។" } },
    { year: "2022 — 2024",
      title: { en: "Reconnaissance Section Leader",            km: "មេបញ្ជា​ការ​ផ្នែក​ស៊ើប​ការណ៍" },
      unit:  { en: "2nd Recon Battalion · Kampong Speu",       km: "កងពលតូចស៊ើបការណ៍​ទី​២ · កំពង់ស្ពឺ" },
      body:  { en: "Commanded an eight-soldier reconnaissance section across rotations in Mondulkiri and Ratanakiri. Wrote the standing patrol order adopted by all four sections in the battalion.",
               km: "បាន​ដឹក​នាំ​ផ្នែក​ស៊ើប​ការណ៍​ប្រាំបី​នាក់ ឆ្លង​កាត់​វេន​នៅ​មណ្ឌលគិរី និង​រតនគិរី។ បាន​សរសេរ​បញ្ជា​ល្បាត​ស្តង់ដារ ដែល​ត្រូវ​បាន​ប្រើ​ដោយ​ផ្នែក​ទាំង​បួន​ក្នុង​កងពលតូច។" } },
    { year: "2020 — 2022",
      title: { en: "Rifle Platoon, Second-in-Command",         km: "ភូមិ​ភាគ​អ៊ីនហ្វង់ទ្រី អនុ​បញ្ជាការ" },
      unit:  { en: "1st Infantry Brigade · Banteay Meanchey",  km: "កងពល​លេខ ​១ · បន្ទាយមានជ័យ" },
      body:  { en: "Built the platoon's land-navigation program and coached three squad leaders into NCO promotion boards.",
               km: "បាន​បង្កើត​កម្មវិធី​ដ្រាយ​ដី​សម្រាប់​ភូមិ​ភាគ និង​បាន​បង្ហាត់​មេក្រុម​បី​នាក់​ចូល​គណៈ​កម្មការ​តម្លើង​ឋានន្តរ​សក្ដិ។" } },
    { year: "2017 — 2020",
      title: { en: "Squad Leader, Mechanized Infantry",        km: "មេក្រុម អ៊ីនហ្វង់ទ្រី​ម៉ាស៊ីន" },
      unit:  { en: "5th Mechanized Battalion · Kampong Cham",  km: "កងពលតូច​ម៉ាស៊ីន​ទី ៥ · កំពង់ចាម" },
      body:  { en: "Led a 10-soldier squad through two annual readiness inspections — top-rated in both. Maintained accountability of $2.5M in sensitive equipment with zero loss.",
               km: "បាន​ដឹក​នាំ​ក្រុម​ទាហាន​ដប់​នាក់ ឆ្លងកាត់​ការ​ត្រួត​ពិនិត្យ​ការ​ត្រៀម​ប្រចាំ​ឆ្នាំ​ពីរ​ដង — ទទួល​បាន​ការ​វាយ​តម្លៃ​កំពូល។ បាន​ថែ​រក្សា​បរិក្ខារ​រសើប ២,៥ លាន​ដុល្លារ ដោយ​គ្មាន​ការ​បាត់​បង់។" } },
    { year: "2016 — 2017",
      title: { en: "Officer Cadet",                            km: "សិក្ខាកាម​នាយទាហាន" },
      unit:  { en: "RCAF Officer Academy · Kampong Speu",      km: "សាលា​នាយទាហាន​យុទ្ធពលខេមរភូមិន្ទ · កំពង់ស្ពឺ" },
      body:  { en: "Graduated 4th of 188. Distinguished Honor Graduate, leadership lane.",
               km: "បាន​បញ្ចប់​លេខ​៤​ក្នុង​ចំណោម ១៨៨​នាក់។ និស្សិត​ឆ្នើម​ផ្នែក​ការ​ដឹក​នាំ។" } },
  ],

  achievements: [
    { tag: { en:"Logistics · 2023", km:"ភ័ស្តុភារ · ២០២៣" },
      title:{ en:"Zero-loss accountability across a brigade rotation",
              km:"គ្មាន​ការ​បាត់​បង់​ក្នុង​វេន​កងពល" },
      s:{ en:"During the brigade's high-tempo Cobra Gold rotation, accountability for woodland-camo issued kit historically slipped 4–6%.", km:"អំឡុង​វេន​ខ្លាំង Cobra Gold បរិក្ខារ​បំពាក់​បាន​បាត់​បង់​ជាប្រវត្តិ​ ៤–៦%។" },
      t:{ en:"Reach 0% loss on $2.5M of sensitive equipment across 230 personnel and 60 days.", km:"ឈាន​ដល់ ០% នៃ​ការ​បាត់​បង់​លើ​បរិក្ខារ​ ២,៥ លាន​ដុល្លារ លើ​បុគ្គលិក ២៣០ នាក់ និង​៦០ ថ្ងៃ។" },
      a:{ en:"Built a daily QR-tagged sensitive-items check, paired soldiers in two-person sign-out, and ran a surprise inventory every fourth night.", km:"បាន​បង្កើត​ការ​ត្រួត​ពិនិត្យ QR ប្រចាំ​ថ្ងៃ ផ្គូផ្គង​ទាហាន​ពីរ​នាក់​ក្នុង​ការ​ចេញ​បរិក្ខារ និង​ធ្វើ​ការ​ត្រួត​ពិនិត្យ​ភ្ញាក់​ផ្អើល​រៀងរាល់​៤​យប់​ម្តង។" },
      r:{ en:"Zero loss across the rotation. Method adopted as the brigade SOP in Q4 2023.", km:"គ្មាន​ការ​បាត់​បង់​ក្នុង​វេន។ វិធី​សាស្ត្រ​ត្រូវ​បាន​អនុម័ត​ជា SOP កងពល​នៅ​ត្រី​មាស​ទី ៤ ឆ្នាំ ២០២៣។" } },

    { tag: { en:"Leadership · 2024", km:"ការ​ដឹក​នាំ · ២០២៤" },
      title:{ en:"Promoted three soldiers to NCO in a single board cycle",
              km:"តម្លើង​ទាហាន​បី​នាក់​ដល់​ឋានន្តរសក្ដិ​ផ្នែក​ក្រោម​នាយ" },
      s:{ en:"Platoon had not produced a board-ready NCO in 18 months.", km:"ភូមិ​ភាគ​មិន​បាន​បង្កើត​ផ្នែក​ក្រោម​នាយ​សម្រាប់​គណៈ​កម្ម​ការ​អស់​រយៈ​ពេល​ ១៨ ​ខែ​ឡើយ។" },
      t:{ en:"Develop credible candidates for the Q2 2024 NCO board.", km:"អភិវឌ្ឍ​បេក្ខភាព​ដែល​មាន​សុចរិតភាព​សម្រាប់​គណៈ​កម្ម​ការ​ត្រី​មាស​ទី​២ ឆ្នាំ ២០២៤។" },
      a:{ en:"Designed a 12-week mentor track: weekly counselling, four written practice boards, and a sponsored land-nav certification.", km:"បាន​រៀបចំ​ផ្លូវ​មេន​​ទរ​ ១២ សប្តាហ៍៖ ការ​ប្រឹក្សា​ប្រចាំ​សប្តាហ៍ គណៈ​កម្ម​ការ​សរសេរ​បួន​ដង និង​ការ​បញ្ជាក់​ដ្រាយ​ដី។" },
      r:{ en:"Three soldiers promoted on first board attempt. The mentor track is now run battalion-wide.", km:"ទាហាន​បី​នាក់​ត្រូវ​បាន​តម្លើង​លើ​ការ​ឡើង​គណៈ​កម្ម​ការ​លើក​ដំបូង។ ផ្លូវ​មេន​​ទរ​ឥឡូវ​ត្រូវ​បាន​ដំណើរ​ការ​ទូទាំង​កងពល​តូច។" } },

    { tag: { en:"Joint Ops · 2022", km:"ប្រតិបត្តិការ​រួម · ២០២២" },
      title:{ en:"Coordinated medevac during Angkor Sentinel exercise",
              km:"សម្របសម្រួល​ការ​ដឹក​ជូន​បន្ទាន់​ក្នុង​លំហាត់ Angkor Sentinel" },
      s:{ en:"Joint exercise with US Pacific partners; a notional casualty cascaded into a real heat-injury during the live phase.", km:"លំហាត់​រួម​ជាមួយ​ដៃ​គូ​សហរដ្ឋ​អាមេរិក; ករណី​ឧប្បត្តិ​ហេតុ​ឆ្លុះ​ក្លាយ​ជា​ការ​ឈឺ​ដោយ​សារ​កំដៅ​ពិត​នៅ​អំឡុង​ដំណាក់​កាល​ផ្ទាល់។" },
      t:{ en:"Get the casualty to a medical asset within the golden hour while keeping the exercise in-tempo.", km:"ដឹក​អ្នក​ឈឺ​ទៅ​មន្ទីរ​ពេទ្យ​ក្នុង​រយៈ​ពេល​មួយ​ម៉ោង​មាស ដោយ​រក្សា​លំហាត់​ឱ្យ​បន្ត​បាន។" },
      a:{ en:"Switched to bilingual radio nets, called the 9-line in English, and ground-guided the partner aircraft to the LZ.", km:"បាន​ប្តូរ​ទៅ​បណ្ដាញ​វិទ្យុ​ពីរ​ភាសា ហៅ​ទម្រង់​៩​ខ្សែ​ជា​ភាសា​អង់គ្លេស និង​ណែ​នាំ​យន្ត​ហោះ​ដៃ​គូ​ទៅ​ដល់​តំបន់​ចុះ​ចត។" },
      r:{ en:"Casualty extracted in 38 minutes. Cited in the joint after-action as exemplary radio discipline.", km:"អ្នក​ឈឺ​ត្រូវ​បាន​ដក​ចេញ​ក្នុង​រយៈ​ពេល ៣៨ នាទី។ ត្រូវ​បាន​ដក​ស្រង់​ក្នុង​របាយការណ៍​បន្ទាប់​ពី​សកម្មភាព​ជា​ឧទាហរណ៍​នៃ​វិន័យ​វិទ្យុ។" } },

    { tag: { en:"Humanitarian · 2020", km:"មនុស្ស​ធម៌ · ២០២០" },
      title:{ en:"Flood-relief patrol, Kampong Cham",
              km:"ល្បាត​សង្គ្រោះ​ទឹក​ជំនន់ កំពង់ចាម" },
      s:{ en:"Mekong flooding cut three rural communes from the district road network.", km:"ទឹក​ជំនន់​ទន្លេ​មេគង្គ​បាន​កាត់​ផ្តាច់​ឃុំ​ដាច់​ស្រយាល​បី ពី​បណ្ដាញ​ផ្លូវ​ស្រុក។" },
      t:{ en:"Re-establish access for medical and food resupply within 72 hours.", km:"បង្កើត​ការ​ចូល​ដំណើរ​ការ​ឡើង​វិញ​សម្រាប់​ការ​ផ្គត់​ផ្គង់​សុខាភិបាល និង​ស្បៀង​ក្នុង​រយៈ​ពេល ៧២ ម៉ោង។" },
      a:{ en:"Led a 10-soldier boat element on six resupply runs; coordinated with Red Cross volunteers and the commune chief network.", km:"បាន​ដឹក​នាំ​ក្រុម​ទូក​ទាហាន ១០ នាក់​ធ្វើ​ការ​ផ្គត់​ផ្គង់​៦​ដង; សម្រប​សម្រួល​ជាមួយ​ស្ម័គ្រ​ចិត្ត​កាកបាទ​ក្រហម និង​បណ្ដាញ​មេឃុំ។" },
      r:{ en:"All three communes resupplied within 60 hours. 1,400+ people received food and clean water.", km:"ឃុំ​ទាំង​បី​ត្រូវ​បាន​ផ្គត់​ផ្គង់​ឡើង​វិញ​ក្នុង​រយៈ​ពេល ៦០ ម៉ោង។ ប្រជាជន​ជាង ១៤០០ នាក់​បាន​ទទួល​ស្បៀង និង​ទឹក​ស្អាត។" } },
  ],

  education: [
    { year:"2023", title:{en:"Airborne Course (Static-Line, Mass Tactical)", km:"វគ្គ​លោត​ឆ័ត្រ (ខ្សែ​ស្តាទិក យុទ្ធវិធី​ច្រើន​នាក់)"}, place:{en:"Brigade 911 Jump School · Phnom Penh", km:"សាលា​លោត​ឆ័ត្រ កងពល​៩១១ · ភ្នំពេញ"}, note:{en:"Distinguished Honor Graduate · 5 qualifying jumps", km:"និស្សិត​ឆ្នើម · លោត​ត្រឹម​ត្រូវ​៥​ដង"} },
    { year:"2022", title:{en:"Jungle Operations Course",                       km:"វគ្គ​ប្រតិបត្តិ​ការ​ព្រៃ"}, place:{en:"RCAF Mountain Warfare School · Mondulkiri", km:"សាលា​យុទ្ធ​ភ្នំ​យុទ្ធពលខេមរភូមិន្ទ · មណ្ឌលគិរី"}, note:{en:"Top three of cohort", km:"បី​នាក់​ខ្ពស់​បំផុត​ក្នុង​ក្រុម"} },
    { year:"2021", title:{en:"Combat Lifesaver Course",                          km:"វគ្គ​សង្គ្រោះ​ជីវិត​សង្គ្រាម"}, place:{en:"Joint US–RCAF training · Sihanoukville", km:"បណ្តុះបណ្ដាល​រួម សហរដ្ឋ​អាមេរិក–យុទ្ធពលខេមរភូមិន្ទ · ខេត្តព្រះសីហនុ"}, note:{en:"Bilingual instruction, EN+KH", km:"បង្រៀន​ពីរ​ភាសា អង់គ្លេស+ខ្មែរ"} },
    { year:"2020", title:{en:"Small-Unit Tactics, Advanced",                     km:"យុទ្ធវិធី​ឯកតា​តូច កម្រិត​ខ្ពស់"}, place:{en:"RCAF Infantry School · Kampong Speu", km:"សាលា​អ៊ីនហ្វង់ទ្រី​យុទ្ធពលខេមរភូមិន្ទ · កំពង់ស្ពឺ"}, note:{en:"Capstone project: night patrol order template", km:"គម្រោង​បញ្ចប់: ទម្រង់​បញ្ជា​ល្បាត​យប់"} },
    { year:"2017", title:{en:"Officer Basic Course",                              km:"វគ្គ​មូលដ្ឋាន​នាយទាហាន"}, place:{en:"RCAF Officer Academy · Kampong Speu", km:"សាលា​នាយទាហាន​យុទ្ធពលខេមរភូមិន្ទ · កំពង់ស្ពឺ"}, note:{en:"Commissioned 2LT · 4 / 188", km:"តែងតាំង​អនុ​សេនីយ៍​ត្រី · ៤ / ១៨៨"} },
    { year:"2016", title:{en:"BA, Public Administration",                         km:"បរិញ្ញាបត្រ រដ្ឋបាលសាធារណៈ"}, place:{en:"Royal University of Phnom Penh", km:"សាកលវិទ្យាល័យភូមិន្ទភ្នំពេញ"}, note:{en:"Magna cum laude", km:"និស្សិត​ឆ្នើម"} },
  ],

  awards: [
    { year:"2024", name:{en:"Sahametrei Medal, Class III",          km:"គ្រឿងឥស្សរិយយស​សហមេត្រី ថ្នាក់​ទី​៣"}, why:{en:"For distinguished service in joint training operations.", km:"សម្រាប់​សេវា​ឆ្នើម​ក្នុង​ប្រតិបត្តិ​ការ​បណ្តុះបណ្តាល​រួម។"} },
    { year:"2023", name:{en:"Brigade Commander's Coin",             km:"កាក់​មេបញ្ជាការ​កងពល"}, why:{en:"Zero-loss accountability across a 60-day rotation.",     km:"ការ​ទទួល​ខុស​ត្រូវ​បរិក្ខារ​គ្មាន​ការ​បាត់​បង់​ឆ្លង​វេន ៦០ ​ថ្ងៃ។"} },
    { year:"2022", name:{en:"Joint Service Commendation",            km:"សារ​សរសើរ​ការ​បម្រើ​រួម"}, why:{en:"Radio-discipline cited during Angkor Sentinel medevac.",  km:"វិន័យ​វិទ្យុ​ក្នុង​ការ​ដឹក​ជូន​បន្ទាន់ Angkor Sentinel។"} },
    { year:"2021", name:{en:"Combat Lifesaver Badge",                km:"គ្រឿង​សង្គ្រោះ​ជីវិត​សង្គ្រាម"}, why:{en:"Successful certification under joint US–RCAF instruction.",km:"ការ​បញ្ជាក់​សម្រេច​ក្រោម​ការ​បណ្តុះបណ្ដាល​រួម។"} },
    { year:"2020", name:{en:"Humanitarian Service Ribbon",           km:"ខ្សែបូ​សេវា​មនុស្ស​ធម៌"}, why:{en:"Mekong flood relief, Kampong Cham — six successful resupply runs.",   km:"សង្គ្រោះ​ទឹក​ជំនន់​មេគង្គ កំពង់ចាម — ៦ ការ​ផ្គត់​ផ្គង់​ជោគ​ជ័យ។"} },
    { year:"2019", name:{en:"Marksman Badge, Expert",                 km:"គ្រឿងបាញ់ កម្រិត​ឯកទេស"}, why:{en:"Top score in battalion qualification, three years running.", km:"ពិន្ទុ​ខ្ពស់​បំផុត​ក្នុង​លក្ខណៈ​សម្បត្តិ​កងពល​តូច​អស់​បី​ឆ្នាំ។"} },
    { year:"2017", name:{en:"Distinguished Honor Graduate",          km:"និស្សិត​ឆ្នើម"}, why:{en:"Officer Basic Course — finished 4 of 188.",                     km:"វគ្គ​មូលដ្ឋាន​នាយទាហាន — បាន​បញ្ចប់​លេខ​៤​ក្នុង​ចំណោម ១៨៨។"} },
  ],

  skills: [
    { group:{en:"Tactical & Field",        km:"យុទ្ធវិធី និង​ផ្ទាល់"}, items:[
      {n:{en:"Small-unit tactics",         km:"យុទ្ធវិធី​ឯកតា​តូច"},     l:5},
      {n:{en:"Airborne / static-line ops", km:"ប្រតិបត្តិការ​ឆ័ត្រ"},     l:4},
      {n:{en:"Land navigation",            km:"ដ្រាយ​ដី"},                l:5},
      {n:{en:"Reconnaissance & patrolling",km:"ស៊ើបការណ៍ និង​ល្បាត"},   l:5},
      {n:{en:"Marksmanship",               km:"ការ​បាញ់"},                l:5},
    ]},
    { group:{en:"Command & Staff",          km:"បញ្ជា និង​បុគ្គលិក"}, items:[
      {n:{en:"Personnel management",        km:"ការ​គ្រប់​គ្រង​បុគ្គលិក"}, l:5},
      {n:{en:"Sensitive-items accountability",km:"ទទួល​ខុស​ត្រូវ​បរិក្ខារ​រសើប"}, l:5},
      {n:{en:"Operations orders (5-paragraph)",km:"បញ្ជា​ប្រតិបត្តិការ"},      l:4},
      {n:{en:"After-action reviews",        km:"ការ​ត្រួត​ពិនិត្យ​ក្រោយ​សកម្មភាព"}, l:4},
    ]},
    { group:{en:"Coordination",             km:"សម្រប​សម្រួល"}, items:[
      {n:{en:"Joint / bilingual coordination",km:"សម្រប​សម្រួល​រួម / ពីរ​ភាសា"}, l:4},
      {n:{en:"Civil–military liaison",      km:"សម្ព័ន្ធ​ភាព​ស៊ីវិល–យោធា"},   l:4},
      {n:{en:"Radio nets & reporting",      km:"បណ្ដាញ​វិទ្យុ និង​របាយការណ៍"}, l:5},
    ]},
  ],

  languages: [
    { name:{en:"Khmer",   km:"ខ្មែរ"},      level:{en:"Native",        km:"ភាសា​កំណើត"},        l:5 },
    { name:{en:"English", km:"អង់គ្លេស"},   level:{en:"Professional",  km:"កម្រិត​វិជ្ជាជីវៈ"}, l:4 },
  ],

  references: [
    { quote:{en:"\u201cOne of the most disciplined platoon leaders I've supervised. Calm under load, sharp on the radio, and absolutely trusted with an inventory.\u201d",
             km:"«គឺ​ជា​មេបញ្ជា​ការ​ភូមិ​ភាគ​ដែល​មាន​វិន័យ​ខ្លាំង​បំផុត​ម្នាក់​ដែល​ខ្ញុំ​ធ្លាប់​ដឹក​នាំ។ ស្ងប់ស្ងាត់​ក្រោម​សម្ពាធ ច្បាស់​លាស់​លើ​វិទ្យុ និង​ជឿ​ទុក​ចិត្ត​លើ​ការ​គ្រប់គ្រង​បរិក្ខារ។»"},
      who:{en:"Lt. Col. Heng Bora · Battalion Commander, 2nd Recon Battalion", km:"វរសេនីយ៍​ឯក ហេង បុរ៉ា · មេបញ្ជាការ​កងពលតូច​ស៊ើបការណ៍​ទី​២"} },
    { quote:{en:"\u201cBuilt our NCO mentor track from nothing. We now graduate three times the candidates we used to.\u201d",
             km:"«បាន​បង្កើត​ផ្លូវ​មេន​​ទរ​ផ្នែក​ក្រោម​នាយ​ពី​សូន្យ។ ឥឡូវ​យើង​បង្កើត​បេក្ខភាព​បី​ដង​ច្រើន​ជាង​មុន។»"},
      who:{en:"Sgt. Maj. Pich Sothy · Senior NCO, Brigade 911", km:"អនុ​សេនីយ៍​ទោ ពេជ្រ សុធី · អនុ​នាយ​ជាន់​ខ្ពស់ កងពល​៩១១"} },
    { quote:{en:"\u201cBilingual radio operator I trusted to call our 9-line in English while we kept the platoon moving. Rare and valuable.\u201d",
             km:"«ប្រតិបត្តិករ​វិទ្យុ​ពីរ​ភាសា​ដែល​ខ្ញុំ​ជឿ​ទុក​ចិត្ត​អោយ​ហៅ​ទម្រង់​៩​ខ្សែ​ជា​ភាសា​អង់គ្លេស ខណៈ​ភូមិ​ភាគ​នៅ​បន្ត​ផ្លាស់​ទី។ កម្រ និង​មាន​តម្លៃ​ខ្លាំង។»"},
      who:{en:"CPT Daniel Whitford · US Army Pacific, Exercise Liaison", km:"ឯកសេនីយ៍​ឯក ដានីយ៉ែល វីត​ហ្វត · ទាហាន​សហរដ្ឋ​ភាគ​ប៉ាស៊ីហ្វិក សម្ព័ន្ធ​លំហាត់"} },
  ],

  contact: {
    email: "sovathana.kun@rcaf.gov.kh",
    phone: "+855 12 345 678",
    duty:  { en: "Brigade 911, B Company HQ — Phnom Penh", km: "កងពល​៩១១ ការិយាល័យ​ក្រុម​ខ — ភ្នំពេញ" },
    note:  { en: "Available for promotion-board review and selection-panel correspondence. Routine messages outside duty hours acknowledged within 24 hours.",
             km: "មាន​ភាព​អាច​រក​បាន​សម្រាប់​ការ​ត្រួត​ពិនិត្យ​គណៈ​កម្ម​ការ​តម្លើង​ឋានន្តរ​សក្ដិ និង​បន្ទះ​ជ្រើស​រើស។ សារ​ក្រៅ​ម៉ោង​ការងារ​ត្រូវ​បាន​ឆ្លើយ​តប​ក្នុង​២៤​ម៉ោង។" },
  },
};
